# Generated by Django 4.2.4 on 2023-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteprint', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_date',
            field=models.CharField(max_length=30, null=True, verbose_name='프린트 날짜'),
        ),
    ]
