# Generated by Django 4.2.4 on 2023-08-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteprint', '0003_order_print_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_pw',
        ),
        migrations.AddField(
            model_name='order',
            name='order_request',
            field=models.CharField(max_length=30, null=True, verbose_name='요청사항'),
        ),
    ]
